name: Unit Test

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - name: Test unit
        run: yarn test
      - name: Validate Browser Bundle
        run: yarn run test-browser-build
      - name: Validate translation
        run: yarn validate-translations
